version: "3"

services:
  app:
    env_file: ".env"
    build:
      context: .
      dockerfile: ./docker/nodejs/Dockerfile
    platform: linux/amd64
    ports:
      - "80:4000"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nomadcoffee

    expose:
      - "5432"
