version: "3"

services:
  app:
    env_file: ".docker.env"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/nomadcoffee?schema: public"
      PORT: 8080
    build:
      context: .
      dockerfile: ./docker/nodejs/Dockerfile
    platform: linux/amd64
    ports:
      - "80:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nomadcoffee
    expose:
      - "5432"
